// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHUHSoGZQjtk4JaWgWymPoZZphwjM3A0M',
    appId: '1:767752664402:web:0345ddf1a9ec7fe482b68b',
    messagingSenderId: '767752664402',
    projectId: 'allumniconnect-ad294',
    authDomain: 'allumniconnect-ad294.firebaseapp.com',
    storageBucket: 'allumniconnect-ad294.firebasestorage.app',
    measurementId: 'G-LJ1YECH73Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdttCxPiix2qHQ7gT_oaK1RxVP0NvvZmc',
    appId: '1:767752664402:android:f45429eda5997ca882b68b',
    messagingSenderId: '767752664402',
    projectId: 'allumniconnect-ad294',
    storageBucket: 'allumniconnect-ad294.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtcqv0ysT7LRLoz4-imK7aJGrvyWgsqGw',
    appId: '1:767752664402:ios:03c14a6aa579479482b68b',
    messagingSenderId: '767752664402',
    projectId: 'allumniconnect-ad294',
    storageBucket: 'allumniconnect-ad294.firebasestorage.app',
    iosBundleId: 'com.allumni.allumniConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtcqv0ysT7LRLoz4-imK7aJGrvyWgsqGw',
    appId: '1:767752664402:ios:03c14a6aa579479482b68b',
    messagingSenderId: '767752664402',
    projectId: 'allumniconnect-ad294',
    storageBucket: 'allumniconnect-ad294.firebasestorage.app',
    iosBundleId: 'com.allumni.allumniConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHUHSoGZQjtk4JaWgWymPoZZphwjM3A0M',
    appId: '1:767752664402:web:12e5bf8506ae50d382b68b',
    messagingSenderId: '767752664402',
    projectId: 'allumniconnect-ad294',
    authDomain: 'allumniconnect-ad294.firebaseapp.com',
    storageBucket: 'allumniconnect-ad294.firebasestorage.app',
    measurementId: 'G-HHE2NX1J42',
  );
}
